extends SceneTree
const Home = preload("res://scripts/homestead.gd")
var checks := 0
var failures := 0
func check(ok: bool, reason: String) -> void:
	checks += 1
	if not ok: failures += 1; push_error(reason)
func _initialize() -> void:
	call_deferred("run")
func run() -> void:
	var profile := Profile.new()
	profile.path = "user://homestead-rules-test.json"
	var home := Home.new(profile)
	check(home.state().plots.size()==9 and home.state().beds==6,"Old profiles get six free plots and no unearned inventory")
	check(home.state().seeds.wheat==0,"No repeating login seed gifts")
	profile.data.coins = 1000
	for crop in Home.CROPS:
		var before: int = profile.data.coins
		home.buy(crop)
		check(home.state().seeds[crop]==1 and profile.data.coins==before-Home.CROPS[crop].price,"Exact seed transaction: "+crop)
		home.plant(0,crop)
		check(home.state().seeds[crop]==0 and home.state().plots[0].crop==crop,"Plant consumes one seed: "+crop)
		var planted: int = home.state().plots[0].planted
		check(home.remaining(0,planted)==Home.CROPS[crop].seconds,"Dry growth time: "+crop)
		home.tend(0)
		check(home.state().plots[0].watered,"Watering persists: "+crop)
		check(home.remaining(0,planted)==int(Home.CROPS[crop].seconds*0.65),"Water reduces total growth time by 35%: "+crop)
		home.tend(0)
		check(home.remaining(0,planted)==int(Home.CROPS[crop].seconds*0.65),"Water cannot be repeatedly stacked: "+crop)
		home.state().plots[0].planted = home.now()-1000
		home.tend(0)
		check(profile.product_count(crop)==3 and home.state().plots[0].crop=="","Harvest produces three instances and clears plot: "+crop)
		home.tend(0)
		check(profile.product_count(crop)==3,"Cannot harvest empty plot twice: "+crop)
	check(home.plant(6,"wheat").contains("尚未"),"Locked beds reject planting")
	check(home.plant(-1,"wheat").contains("尚未"),"Invalid negative plot rejected")
	check(home.plant(0,"unknown").contains("不足"),"Invalid crop rejected")
	profile.data.coins = 0
	home.buy("rod")
	check(home.state().rod==0 and profile.data.coins==0,"No purchase without funds")
	profile.data.coins = 1000
	home.buy("beds")
	check(home.state().beds==9 and profile.data.coins==880,"One permanent bed upgrade costs 120")
	home.buy("beds")
	check(profile.data.coins==880,"Cannot repurchase expansion")
	check(not home.cast().is_empty(),"Fishing requires rod")
	home.buy("rod")
	check(home.state().rod==1 and profile.data.coins==810,"Wood rod costs 70")
	check(not home.cast().is_empty(),"Fishing requires bait")
	home.buy("bait")
	check(home.state().bait==5 and profile.data.coins==795,"Bait pack costs 15 for five")
	check(home.cast()=="" and home.state().bait==4,"A cast pays exactly one bait")
	check(not home.cast().is_empty() and home.state().bait==4,"Cast cooldown blocks spam without extra charge")
	home.catch_fish(1.0,0.0)
	check(profile.product_count("silver")==1,"Basic successful catch enters storage as an instance")
	home.catch_fish(1.0,0.99)
	check(profile.product_count("gold")==0,"A cast cannot be rewarded twice")
	home.buy("rod")
	check(home.state().rod==2 and profile.data.coins==615,"Fine rod upgrade costs 180")
	home.buy("rod")
	check(profile.data.coins==615,"Rod is permanent and capped")
	home.state().last_cast = 0
	home.cast()
	home.catch_fish(1.0,0.99)
	check(profile.product_count("gold")==1,"Precise upgraded catch can yield rare fish")
	home.state().last_cast = 0
	home.cast()
	home.catch_fish(0.0,0.99)
	check(profile.product_count("gold")==1,"Missed timing yields no reward")
	home.state().last_cast = 0
	home.cast()
	home.cancel_cast()
	home.catch_fish(1.0,0.99)
	check(profile.product_count("gold")==1,"Closing a cast prevents subsequent reward")
	home.cook("bread")
	check(profile.product_count("wheat")==0 and home.state().meals.bread==1,"Recipe consumes exact ingredient instances")
	home.cook("bread")
	check(home.state().meals.bread==1,"Missing ingredients prevent duplicate cooking")
	home.prepare("bread")
	check(home.state().prepared=="bread" and home.state().meals.bread==1,"Readying food reserves without consuming")
	home.prepare("")
	check(home.state().meals.bread==1 and home.state().prepared=="","Cancellation costs nothing")
	home.prepare("bread")
	var loaded := Profile.new()
	loaded.path = profile.path
	loaded.load_profile()
	check(loaded.data.home==profile.data.home,"Complete homestead survives JSON save/load")
	var session := TideSession.new()
	root.add_child(session)
	session.set_physics_process(false)
	var base: Dictionary = session.make_player(1,{"hero":0})
	var bread: Dictionary = session.make_player(1,{"hero":0,"home_meal":"bread"})
	check(bread.hp==base.hp+24 and session.stat_max_hp(bread)==base.max_hp+24,"Food applies to spawn HP and subsequent gear recalculation")
	var stew: Dictionary = session.make_player(1,{"hero":0,"home_meal":"stew"})
	check(is_equal_approx(session.weapon_damage(stew,0),session.weapon_damage(base,0)*1.12),"Food modifies real weapon damage")
	check(is_equal_approx(session.ultimate_damage(stew,100.0),session.ultimate_damage(base,100.0)*1.12),"Food modifies ultimate damage consistently")
	var tea: Dictionary = session.make_player(1,{"hero":0,"home_meal":"tea"})
	check(Home.bonus(tea,"speed")==24 and tea.hp==base.hp+12,"Fish soup has bounded speed and HP bonus")
	check(session.make_player(1,{"home_meal":"invalid"}).home_meal=="","Network configuration rejects unknown meal IDs")
	session.solo({"home_meal":"bread"})
	session.players[2]=session.make_player(2,{})
	session.players[2].ready=false
	check(not session.launch() and home.state().meals.bread==1,"Rejected launch leaves food inventory unchanged")
	session.players.erase(2)
	session.started.connect(func(): home.consume_started(str(session.players[1].home_meal)))
	check(session.launch(false,1729),"Valid launch succeeds")
	check(home.state().meals.bread==0 and home.state().prepared=="","Successful launch consumes exactly one")
	check(session.players[1].home_meal=="bread","Bonus survives lobby player reconstruction")
	loaded.apply_data({"version":1})
	check(loaded.data.home.rod==0 and loaded.data.home.meals.bread==0,"Switching to old account cannot inherit another account home")
	var malformed := Home.clean({"seeds":[],"stock":{"wheat":-40},"plots":[{"crop":"fake","planted":"x"}],"rod":99,"beds":7,"prepared":"fake"})
	check(malformed.rod==2 and malformed.beds==6 and malformed.plots[0].crop=="" and malformed.stock.wheat==0,"Malformed saves repaired without invalid crops or negative stocks")
	check(Home.clean({"bait":INF}).bait==0,"Non-finite values rejected")
	session.queue_free()
	await process_frame
	DirAccess.remove_absolute(profile.path)
	print("HOMESTEAD: ",checks," checks, ",failures," failures")
	quit(1 if failures else 0)
